<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="style.css">
</head>
<body>
    <section class="semua">
        <div class="layar">
        <div class="konten">
            <h1>THE NECROMANCER'S BANE</h1>
            <p>DUNIA ELDARION, YANG DULU DIPENUHI KEHIDUPAN DAN CAHAYA, KINI TERJERAT DALAM KEGELAPAN. LANGIT YANG PERNAH BIRU KINI <br>
               ABU-ABU KELAM, DISELIMUTI KABUT TEBAL YANG MEMBAWA AROMA KEMATIAN. HUTAN-HUTAN HIJAU BERUBAH MENJADI TANAH TANDUS, DIHUNI OLEH<br>
               MAKHLUK-MAKHLUK TAK BERNYAWA YANG BERGERAK DENGAN GERAKAN KAKU DAN MATA KOSONG. KOTA-KOTA MEGAH YANG RAMAI DENGAN TAWA<br>
               KINI HANYA MENYISAKAN PUING PUING DAN KEHENINGAN MENCEKAM. SEMUA INI ADALAH ULAH MALTHERION, NECROMANCER KEGELAPAN, YANG<br>
               MEMBANGKITKAN PASUKAN MAYAT HIDUP UNTUK MENEBAR TEROR. NAMUN, DI TENGAH KEPUTUSASAAN, SEBUAH HARAPAN MUNCUL: SEORANG <br>
               PAHLAWAN YANG TAK MENYADARI TAKDIRNYA, MEMUTUSKAN UNTUK MENDAFTAR DI AKADEMI ARANTHOR, TEMPAT PARA KESATRIA DAN PENYIHIR <br>
               TERBAIK DILATIH UNTUK MELAWAN ANCAMAN YANG MENGANCAM ELDARION. DI SANA, IA AKAN MENEMUKAN JAWABAN TENTANG KEKUATAN YANG <br>
               TERSEMBUNYI DALAM DIRINYA DAN MEMULAI PERJALANAN YANG AKAN MENENTUKAN NASIB DUNIA. </p>
        </div>
        <div class="kirim">
                <a href="login.php">MEMULAI PERJALANAN</a>
        </div>
        </div>
    </section>
</body>
</html>